import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const targetUrl = event.notification.data?.url || '/dues'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window client is already open, focus it
      for (const client of clientList) {
        const clientUrl = new URL(client.url)
        if (clientUrl.pathname === targetUrl || client.visibilityState === 'visible') {
          return client.focus().then(() => {
            // Also post message to client to navigate if needed
            return client.navigate(targetUrl)
          })
        }
      }
      // Otherwise, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl)
      }
    })
  )
})

// Handle periodic sync events - communicate back to app clients to perform daily checks
self.addEventListener('periodicsync', (event) => {
  if (event.tag === 'daily-due-check') {
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
        clientList.forEach((client) => {
          client.postMessage({
            type: 'PERIODIC_SYNC_TRIGGER'
          })
        })
      })
    )
  }
})

// Handle push event (no-op stub for PWA standard requirements)
self.addEventListener('push', (event) => {
  // Silent push / MVP placeholder
  console.log('[Service Worker] Push event received: ', event)
})
